### ISSUE TITLE
Padding required on UI

### ISSUE THREAD

**Issue by masonlr** [alan-turing-institute/gateway-frontend#100]
The current spacing cuts off the text off the units. We need to pad the input boxes so that this doesn't happen.

<img width="282" alt="screen shot 2018-01-04 at 3 34 23 pm" src="https://user-images.githubusercontent.com/5828176/34571028-69224d00-f165-11e7-9f50-dcc22543f1e9.png">
<img width="278" alt="screen shot 2018-01-04 at 3 34 28 pm" src="https://user-images.githubusercontent.com/5828176/34571029-6a1379be-f165-11e7-968e-438d4c3e02a3.png">

Also, let's look at using unicode superscript in the json input, for example "kg/m³" instead of "kg/m3".

**Comment by myyong** [comment]
resolved
