### ISSUE TITLE
Multiple clicks on "Run" are possible

### ISSUE THREAD

**Issue by masonlr** [alan-turing-institute/gateway-frontend#101]
Submission modal needs to block user from clicking "Run" multiple times.

<img width="732" alt="screen shot 2018-01-04 at 5 21 58 pm" src="https://user-images.githubusercontent.com/5828176/34575761-cbb0e630-f173-11e7-9149-3dabbfc8715d.png">

**Comment by masonlr** [comment]
If the job takes a long time to copy across and commence running, the appearance of the submission modal is delayed. It needs to appear earlier, immediately after clicking "Run".

**Comment by myyong** [comment]
Disabled Run button after saving changes. Resolved.
