### ISSUE TITLE
Loading spinner shows for empty dashboard

### ISSUE THREAD

**Issue by masonlr** [alan-turing-institute/gateway-frontend#103]
If the dashboard is empty, a continuous loading spinner is shown. The spinner should instead be temporary.

<img width="933" alt="screen shot 2018-01-09 at 9 36 59 am" src="https://user-images.githubusercontent.com/5828176/34714238-bd1a69ce-f520-11e7-9305-1224f66d1789.png">

**Comment by myyong** [comment]
Spinner removed
