### ISSUE TITLE
Pagination for dashboard

### ISSUE THREAD

**Issue by myyong** [alan-turing-institute/gateway-frontend#106]
**Objective**
Get xx jobs per page

**Criteria**
1. Offer options for number of jobs per page
2. Get X number of jobs
3. Paginate

**Comment by masonlr** [comment]
Closing this issue as ant.design tables have automatic client-side pagination. At this stage we are not using server-side pagination (i.e. we aren't including pagination arguments in the API queries, we are requesting all case/job summaries and relying on client-side pagination).
