### ISSUE TITLE
Integration testing

### ISSUE THREAD

**Issue by myyong** [alan-turing-institute/gateway-frontend#42]
Comments refer to branch `42-integration-testing`

**Comment by masonlr** [comment]
- [ ] transparent/greyed out "save" button when state is clean. Opaque "save" button when status is dirty

**Comment by masonlr** [comment]
- [ ] Buttons overflow with some browser widths

<img width="743" alt="screen shot 2017-08-31 at 6 39 44 pm" src="https://user-images.githubusercontent.com/5828176/29936944-d0ba6f1c-8e7b-11e7-9628-93c634d36d98.png">

**Comment by masonlr** [comment]
`saveJob()` is using the `newJobUrl` (i.e. `environment.apiUrl+"jobs"`). Check whether `saveJob()` should instead be calling `PUT` on `api/jobs/<job-id>`.

```  saveJob(jobData:any, newJobUrl): Observable<InputComponent[]> {
    console.log("in save")
    let headers = new Headers({ 'Content-Type': 'application/json' });
    let options = new RequestOptions({ headers: headers });
    let response = this.http.patch(newJobUrl, jobData, options)
                    .catch(this.handleError);
    return response
  }
```

**Comment by myyong** [comment]
> Okay as this.http.patch is used. I think that it is confusing to have newJobUrl as a variable name if the URL is serving multiple purposes. Renaming to jobsUrl may be less confusing.

Agreed, have changed this.

**Comment by masonlr** [comment]
Closing due to migration to ant.design.
